puts "The students of Villains Academy"
puts "-------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Jason Voorhes"
puts "The Wicked Witch of the West"
puts "The Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Michael Myers"
puts "Norman Bates"
